"""add outbox messages table

Revision ID: 050bb71e74d2
Revises:
Create Date: 2026-07-26 13:04:32.780470+00:00

Review checklist before merging:

* Does ``downgrade()`` actually reverse ``upgrade()``? A migration you cannot
  roll back is a migration you cannot deploy safely.
* Does this lock a large table? ``ALTER TABLE ... ADD COLUMN NOT NULL`` without
  a default rewrites the whole table and blocks writes for its duration.
* Are new indexes created ``CONCURRENTLY``? A plain ``CREATE INDEX`` blocks
  writes; note that concurrent creation cannot run inside a transaction.
* Is this backwards compatible with the currently deployed code? During a
  rolling deploy both versions run at once, so destructive changes need two
  releases: stop using the column, then drop it.
* Does a data migration handle an empty table, and is it batched for a large one?
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "050bb71e74d2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
    )
    op.create_index(
        "ix_outbox_messages_pending",
        "outbox_messages",
        ["next_attempt_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_index(
        "ix_outbox_messages_published_at",
        "outbox_messages",
        ["published_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbox_messages_published_at",
        table_name="outbox_messages",
        postgresql_where=sa.text("published_at IS NOT NULL"),
    )
    op.drop_index(
        "ix_outbox_messages_pending",
        table_name="outbox_messages",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
