"""Reusable model mixins.

Why this file exists
--------------------
Almost every table needs a surrogate primary key and audit timestamps. Copying
those three columns into two hundred models guarantees they will drift — one
model will use a naive timestamp, another will forget ``onupdate``, a third
will index the wrong column.

Mixins let a model declare intent by inheritance (``class Invoice(Base,
UUIDPrimaryKeyMixin, TimestampMixin)``) while the definitions live in one place.
Because they use ``declared_attr`` semantics via ``MappedAsDataclass``-free
plain annotations, they compose freely and stay invisible in the model body.

Design rules
------------
* A mixin adds columns or column-level behaviour only. Query behaviour (for
  example "exclude soft-deleted rows") belongs in the repository layer, where
  it can be seen and overridden.
* Timestamps are set by the *database* (``server_default``/``onupdate``), not by
  Python, so rows written by migrations or admin SQL are also correct.
"""

from datetime import datetime
from uuid import UUID

from sqlalchemy import DateTime, func, text
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    """Adds a UUID surrogate primary key generated by the database.

    UUIDs over auto-increment integers: identifiers can be minted client-side,
    they do not leak row counts, and they survive merging data across shards or
    environments. ``gen_random_uuid()`` requires PostgreSQL 13+.
    """

    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Adds database-managed ``created_at`` / ``updated_at`` audit columns.

    Both are timezone-aware and default server-side, so any write path — ORM,
    raw SQL, migration — produces consistent values.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Adds a nullable ``deleted_at`` marking logical deletion.

    A row with ``deleted_at IS NOT NULL`` must be treated as absent by every
    read path. Enforcing that is the repository's job — a model cannot enforce
    it, and relying on developers to remember the filter at each call site is
    how deleted records reappear in exports.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        default=None,
        index=True,
    )

    @property
    def is_deleted(self) -> bool:
        """Whether the row is logically deleted."""
        return self.deleted_at is not None


# TODO: add a `TenantMixin` (tenant_id + index) once multi-tenancy is designed;
# the row-level isolation strategy must be decided before the first tenant table.
# TODO: add an `OptimisticLockMixin` (version_id column) for records where
# concurrent edits must not silently overwrite each other.
