"""Database constraint naming convention.

Why this file exists
--------------------
PostgreSQL auto-generates names for unnamed constraints and indexes
(``users_email_key``, ``users_email_fkey1``). Those names differ between what
SQLAlchemy's metadata knows and what the database actually created, and Alembic
autogenerate cannot reliably drop a constraint whose name it cannot predict.
The result is migrations that apply on a fresh database and fail on production.

Applying an explicit convention to ``MetaData`` fixes this permanently: every
constraint gets a deterministic name derived from its table and columns, so
autogenerated migrations are stable and reversible.

This convention must be set **before** the first migration is generated.
Changing it later requires renaming every existing constraint in a migration.
"""

from typing import Final

#: Token meanings:
#:   %(table_s)     table name
#:   %(column_0_N_name)s   underscore-joined names of all columns
#:   %(constraint_name)s   the name given to a CheckConstraint
#:   %(referred_table_s)   target table of a foreign key
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

#: Schema every model lives in unless it explicitly overrides ``__table_args__``.
DEFAULT_SCHEMA: Final[str | None] = None

# TODO: if multi-tenancy uses schema-per-tenant, document here how the schema
# is swapped at session level (SET search_path) rather than per model.
