"""Request-scoped ambient context.

Why this file exists
--------------------
Some values are needed almost everywhere and belong in almost no signature: the
request ID a log line should carry, the tenant a query must be scoped to, the
user an audit record should name. Threading them through every function from
router to repository would add a parameter to hundreds of call sites and be
forgotten in exactly the places it matters.

``ContextVar`` solves this correctly for async code. Each task gets its own
view, so two concurrent requests never see each other's values — which is the
reason a module-level global cannot be used here, and why this is not simply a
disguised singleton.

Rules
-----
* **Set at the edge only.** Middleware and dependencies populate the context;
  nothing deeper writes to it. A service that sets ``tenant_id`` has made the
  isolation boundary un-auditable.
* **Read, never trust blindly.** :func:`require_tenant_id` raises when the
  context is empty rather than returning ``None``, because a tenant-scoped query
  that silently runs unscoped is a cross-tenant data leak.
* **Not a request bag.** Anything a function genuinely needs should be an
  argument. This is for cross-cutting identity and correlation only.

See ``docs/architecture/request-lifecycle.md``.
"""

from collections.abc import AsyncIterator, Callable
from contextlib import asynccontextmanager
from contextvars import ContextVar
from dataclasses import dataclass
from functools import partial
from uuid import UUID

#: Unique per HTTP request, generated by the request-context middleware.
#: Attached to every log record and echoed in the response headers.
request_id_var: ContextVar[str | None] = ContextVar("request_id", default=None)

#: Shared across every service hop in one logical operation. Arrives from an
#: upstream caller's header when present; otherwise it mirrors the request ID.
#: This is what makes a single user action traceable across service boundaries.
correlation_id_var: ContextVar[str | None] = ContextVar("correlation_id", default=None)

#: Tenant owning the current request. Set by the tenant-resolution dependency
#: after authentication, and read by the repository layer to scope every query.
tenant_id_var: ContextVar[UUID | None] = ContextVar("tenant_id", default=None)

#: Authenticated principal. Read by the audit layer; never used for
#: authorization decisions, which must go through an explicit dependency.
user_id_var: ContextVar[UUID | None] = ContextVar("user_id", default=None)


@dataclass(frozen=True, slots=True)
class RequestContext:
    """Immutable snapshot of the ambient context.

    Useful when context must cross into a place where the ``ContextVar`` view
    does not follow — a background task, a queued job payload, a thread pool.
    Capture it explicitly rather than assuming propagation.
    """

    request_id: str | None
    correlation_id: str | None
    tenant_id: UUID | None
    user_id: UUID | None


def current_context() -> RequestContext:
    """Capture the ambient context as a value object."""
    return RequestContext(
        request_id=request_id_var.get(),
        correlation_id=correlation_id_var.get(),
        tenant_id=tenant_id_var.get(),
        user_id=user_id_var.get(),
    )


def get_request_id() -> str | None:
    """Return the current request ID, if one has been set."""
    return request_id_var.get()


def get_correlation_id() -> str | None:
    """Return the current correlation ID, if one has been set."""
    return correlation_id_var.get()


def get_tenant_id() -> UUID | None:
    """Return the current tenant ID, or ``None`` outside a tenant scope."""
    return tenant_id_var.get()


def require_tenant_id() -> UUID:
    """Return the current tenant ID, refusing to proceed without one.

    Raising rather than returning ``None`` is deliberate. The alternative —
    a query that quietly runs without a tenant filter — returns every tenant's
    rows, and nothing in the response says so. Failing loudly turns a silent
    data breach into a 500 and a stack trace.

    Returns:
        The tenant ID bound to this request.

    Raises:
        RuntimeError: When no tenant is bound. Always a programming error:
            either the endpoint is missing its tenant dependency, or
            tenant-scoped code is running in a context that has no tenant.
    """
    tenant_id = tenant_id_var.get()
    if tenant_id is None:
        raise RuntimeError(
            "No tenant in context. Tenant-scoped code must run inside a request "
            "carrying a tenant, or within an explicit `tenant_scope(...)` block."
        )
    return tenant_id


def get_user_id() -> UUID | None:
    """Return the authenticated user ID, or ``None`` for anonymous requests."""
    return user_id_var.get()


@asynccontextmanager
async def tenant_scope(tenant_id: UUID) -> AsyncIterator[UUID]:
    """Bind a tenant for the duration of a block.

    Workers, scheduled jobs and scripts operate on tenant data with no request
    to carry the context. Without this they would either have to pass a tenant
    into every repository call — reintroducing the parameter this module exists
    to remove — or bypass
    :class:`~app.infrastructure.database.repository.TenantRepository` entirely,
    which is how a background job ends up reading every tenant's rows.

    Restores the previous value on exit rather than clearing it, so nesting
    behaves correctly: a job that processes tenant A, dips into tenant B for a
    lookup, and returns, finds itself back in A.

    Usage::

        async with tenant_scope(tenant_id):
            async with session_scope() as session:
                invoices = await InvoiceRepository(session).list(params=params)

    Args:
        tenant_id: The tenant to operate as.

    Yields:
        The bound tenant ID, for convenience.
    """
    token = tenant_id_var.set(tenant_id)
    try:
        yield tenant_id
    finally:
        tenant_id_var.reset(token)


@asynccontextmanager
async def user_scope(user_id: UUID) -> AsyncIterator[UUID]:
    """Bind an acting user for the duration of a block.

    The counterpart to :func:`tenant_scope` for attribution. An audit row
    written by a background job should name whoever triggered it, not appear as
    an anonymous system action — "who deleted this?" is the question audit
    trails exist to answer.

    Args:
        user_id: The user to attribute actions to.

    Yields:
        The bound user ID.
    """
    token = user_id_var.set(user_id)
    try:
        yield user_id
    finally:
        user_id_var.reset(token)


@asynccontextmanager
async def request_scope(
    *,
    request_id: str | None = None,
    correlation_id: str | None = None,
    tenant_id: UUID | None = None,
    user_id: UUID | None = None,
) -> AsyncIterator[RequestContext]:
    """Rebind a whole captured context.

    The inverse of :func:`current_context`. A job dispatched from a request
    carries the correlation ID in its payload; restoring it here is what keeps
    the job's log lines attached to the user action that caused it, across a
    process boundary.

    Only the values supplied are bound; the rest are left as they are.

    Yields:
        The context that is now in effect.
    """
    # Partials rather than (var, token) pairs: a heterogeneous list of pairs
    # loses the correlation between a ContextVar and its own token type, and
    # resetting one var with another's token is a bug a checker should catch.
    resets: list[Callable[[], None]] = []
    if request_id is not None:
        resets.append(partial(request_id_var.reset, request_id_var.set(request_id)))
    if correlation_id is not None:
        resets.append(
            partial(correlation_id_var.reset, correlation_id_var.set(correlation_id))
        )
    if tenant_id is not None:
        resets.append(partial(tenant_id_var.reset, tenant_id_var.set(tenant_id)))
    if user_id is not None:
        resets.append(partial(user_id_var.reset, user_id_var.set(user_id)))

    try:
        yield current_context()
    finally:
        # Reverse order, so nested binds unwind the way they were made.
        for reset in reversed(resets):
            reset()
