"""Request-scoped ambient context.

Why this file exists
--------------------
Some values are needed almost everywhere and belong in almost no signature: the
request ID a log line should carry, the tenant a query must be scoped to, the
user an audit record should name. Threading them through every function from
router to repository would add a parameter to hundreds of call sites and be
forgotten in exactly the places it matters.

``ContextVar`` solves this correctly for async code. Each task gets its own
view, so two concurrent requests never see each other's values — which is the
reason a module-level global cannot be used here, and why this is not simply a
disguised singleton.

Rules
-----
* **Set at the edge only.** Middleware and dependencies populate the context;
  nothing deeper writes to it. A service that sets ``tenant_id`` has made the
  isolation boundary un-auditable.
* **Read, never trust blindly.** :func:`require_tenant_id` raises when the
  context is empty rather than returning ``None``, because a tenant-scoped query
  that silently runs unscoped is a cross-tenant data leak.
* **Not a request bag.** Anything a function genuinely needs should be an
  argument. This is for cross-cutting identity and correlation only.

See ``docs/architecture/request-lifecycle.md``.
"""

from contextvars import ContextVar
from dataclasses import dataclass
from uuid import UUID

#: Unique per HTTP request, generated by the request-context middleware.
#: Attached to every log record and echoed in the response headers.
request_id_var: ContextVar[str | None] = ContextVar("request_id", default=None)

#: Shared across every service hop in one logical operation. Arrives from an
#: upstream caller's header when present; otherwise it mirrors the request ID.
#: This is what makes a single user action traceable across service boundaries.
correlation_id_var: ContextVar[str | None] = ContextVar("correlation_id", default=None)

#: Tenant owning the current request. Set by the tenant-resolution dependency
#: after authentication, and read by the repository layer to scope every query.
tenant_id_var: ContextVar[UUID | None] = ContextVar("tenant_id", default=None)

#: Authenticated principal. Read by the audit layer; never used for
#: authorization decisions, which must go through an explicit dependency.
user_id_var: ContextVar[UUID | None] = ContextVar("user_id", default=None)


@dataclass(frozen=True, slots=True)
class RequestContext:
    """Immutable snapshot of the ambient context.

    Useful when context must cross into a place where the ``ContextVar`` view
    does not follow — a background task, a queued job payload, a thread pool.
    Capture it explicitly rather than assuming propagation.
    """

    request_id: str | None
    correlation_id: str | None
    tenant_id: UUID | None
    user_id: UUID | None


def current_context() -> RequestContext:
    """Capture the ambient context as a value object."""
    return RequestContext(
        request_id=request_id_var.get(),
        correlation_id=correlation_id_var.get(),
        tenant_id=tenant_id_var.get(),
        user_id=user_id_var.get(),
    )


def get_request_id() -> str | None:
    """Return the current request ID, if one has been set."""
    return request_id_var.get()


def get_correlation_id() -> str | None:
    """Return the current correlation ID, if one has been set."""
    return correlation_id_var.get()


def get_tenant_id() -> UUID | None:
    """Return the current tenant ID, or ``None`` outside a tenant scope."""
    return tenant_id_var.get()


def require_tenant_id() -> UUID:
    """Return the current tenant ID, refusing to proceed without one.

    Raising rather than returning ``None`` is deliberate. The alternative —
    a query that quietly runs without a tenant filter — returns every tenant's
    rows, and nothing in the response says so. Failing loudly turns a silent
    data breach into a 500 and a stack trace.

    Returns:
        The tenant ID bound to this request.

    Raises:
        RuntimeError: When no tenant is bound. Always a programming error:
            either the endpoint is missing its tenant dependency, or
            tenant-scoped code is running in a context that has no tenant.
    """
    tenant_id = tenant_id_var.get()
    if tenant_id is None:
        raise RuntimeError(
            "No tenant in context. Tenant-scoped code must run inside a request "
            "carrying a tenant, or within an explicit `tenant_scope(...)` block."
        )
    return tenant_id


def get_user_id() -> UUID | None:
    """Return the authenticated user ID, or ``None`` for anonymous requests."""
    return user_id_var.get()


# TODO: add a `tenant_scope(tenant_id)` async context manager for workers and
# scripts that must operate on one tenant's data outside a request, so the same
# repository scoping applies there without special-casing.
